development:
  adapter: postgresql
  encoding: unicode
  database: ga_development
  pool: 5
  host: localhost
  username: larrybuch
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ga_production
  pool: 5
  host: localhost
  username: larrybuch
  password: